---
- name: Install Apache and deploy web page
  hosts: servers
  become: true

  vars:
    web_root: /var/www/html

  tasks:
    - name: Install httpd and php
      yum:
        name:
          - httpd
          - php
        state: present

    - name: Ensure httpd is started and enabled
      service:
        name: httpd
        state: started
        enabled: true

    - name: Deploy index.php template
      template:
        src: index.php.j2
        dest: "{{ web_root }}/index.php"
        mode: '0644'
